[project]
name = "odoo-addons-oca-edi"
version = "17.0.20240202.0"
dependencies = [
    "odoo-addon-base_edi>=17.0dev,<17.1dev",
    "odoo-addon-pdf_helper>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
